# Default config for EDU ASR (Option 2 variant)
model_size: medium.en
language: en
device: cpu
compute_type: int8        # keep this; great on Mac CPU
vad: true
batch_size: 8
diarization: true
diarization_backend: pyannote   # pyannote|simple
min_speaker_count: 1
max_speaker_count: 15
hf_token_env: HF_TOKEN
segment_max_duration_s: 30
write_srt: true
write_vtt: true
write_json: true
write_txt: true