# LM Studio Summarizer Configuration
summarizer:
  # LM Studio API settings
  lm_studio_url: "http://127.0.0.1:1234"
  model_name: "meta-llama-3.1-8b-instruct"  # Adjust to match your loaded model name in LM Studio
  
  # Generation parameters
  max_tokens: 512
  temperature: 0.7
  timeout: 60
  
  # Custom prompt template for educational transcripts
  summary_prompt: |
    Please provide a concise summary of this educational transcript in 1-3 paragraphs. Focus on main topics and themes discussed. Maximize the usefulness of this summary for someone later looking to qualitatively code this transcript.
    
    Keep the summary professional and suitable for educational research purposes.
    
    Transcript:
    {transcript_text}
    
    Summary:

