# Default config for EDU ASR (Option 2 variant)
model_size: medium.en
language: en
device: mps                  # mps|cpu|cuda
compute_type: int8           # float16|int8_float16|int8|auto
vad: true
denoise: false
batch_size: 8
diarization: true
diarization_backend: pyannote   # pyannote|simple
min_speaker_count: 2
max_speaker_count: 6
hf_token_env: HF_TOKEN
segment_max_duration_s: 300
write_srt: true
write_vtt: true
write_json: true
write_txt: true
